# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 56eb7eb1b7272b0646e57e21528ae670062c79dcd8b4b8e2f2683a8237fb441de0b4cf4566214449498d2130f23b4feeb4bbb5f10bd5839d13df68f11070326f

test:
  secret_key_base: 70a49ab744ec99e9786b8e49dd5d052cc4d331bf31b40164a164734dcb62a4b3f5a7eaf96074a32d4039ea8421cf29d020267c4de794e7998f0a964de300f821

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
